$env:KAFKA_NODE_ID = "1"
$env:KAFKA_CONTROLLER_QUORUM_VOTERS = "1@localhost:9093"
$env:KAFKA_LISTENERS = "PLAINTEXT://localhost:9092,CONTROLLER://localhost:9093"
$env:KAFKA_ADVERTISED_LISTENERS = "PLAINTEXT://localhost:9092"